### ISSUE TITLE
Shedule.sh bug

### ISSUE THREAD

**Issue by ShaBangBinBash** [ericallenpaul/Zabbix-Twilio.sh#3]
if [ $COUNTER -eq ${#PHONE[@]-1} ];
should be
if [ $COUNTER -eq ${#PHONE[@]} ];
or produces an error in bash.

Also equates to wrong number as COUNTER++ precedes this, so you are checking the following
COUNTER goes from 1 to x
PHONE goes from 0 to 2
This will skip item 0 every time

**Comment by ericallenpaul** [comment]
Fixed. Thanks for pointing this out.
